#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "✨ Vérification du code avant commit..."

# 1. Vérifie les erreurs de syntaxe
npm run lint || exit 1

# 2. Formate les fichiers
npx prettier --write .

echo "✅ Code propre ! Commit autorisé."